### ISSUE TITLE
Analytic function does not originate from dependencies

### ISSUE THREAD

**Issue by maxmzkr** [cloudera/ibis#900]
I have run into an issue where I am unable to add a fully functioning analytic column to a table expression after filtering on a column not original to the table.

```python
import ibis

t = ibis.table((('col', 'int32'), ), name='t')

# can be any added column e.g. t['col'].name('filter') raises an exception too
t = t[t.columns + [ibis.null().name('filter')]]

# can be any comparison, removing this line lets everything work
t = t[t['filter'].isnull()]

# removing this line lets everything work
t = t[['col']]

# Non analytic functions work here, i.e. (t['col'] + 1).name('count')
count = t.count().name('count')
t = t[t.columns + [count]]

# compiles fine and looks 100% correct
print ibis.impala.compile(t)

t[t.columns]  # fails here
```

```
Traceback (most recent call last):
  File "ibis_fail.py", line 14, in <module>
    t[t.columns]
  File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/ibis/expr/types.py", line 607, in __getitem__
    return self.projection(what)
  File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/ibis/expr/api.py", line 2058, in projection
    op = projector.get_result()
  File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/ibis/expr/analysis.py", line 685, in get_result
    fused_op = self._check_fusion(roots[0])
  File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/ibis/expr/analysis.py", line 725, in _check_fusion
    elif validator.validate(lifted_val):
  File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/ibis/expr/analysis.py", line 764, in validate
    if self._among_roots(op.table.op()):
  File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/ibis/expr/analysis.py", line 777, in _among_roots
    return self.roots_shared(node) > 0
  File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/ibis/expr/analysis.py", line 782, in roots_shared
    if root.is_ancestor(node):
  File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/ibis/expr/operations.py", line 1746, in is_ancestor
    reboxed = Selection(table, self.selections)
  File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/ibis/expr/operations.py", line 1673, in __init__
    self._validate(dependent_exprs)
  File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/ibis/expr/operations.py", line 1694, in _validate
    self.table._assert_valid(exprs)
  File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/ibis/expr/types.py", line 576, in _assert_valid
    ExprValidator([self]).validate_all(exprs)
  File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/ibis/expr/analysis.py", line 805, in validate_all
    self.assert_valid(expr)
  File "/pipedream/local/venv/deepfield-env/lib/python2.7/site-packages/ibis/expr/analysis.py", line 810, in assert_valid
    raise RelationError(msg)
ibis.common.RelationError: The expression ref_0
UnboundTable[table]
  name: t
  schema:
    col : int32

ref_1
Selection[table]
  table:
    Table: ref_0
  selections:
    col = Column[array(int32)] 'col' from table 
      ref_0
    filter = NullLiteral[null]
      None

ref_2
Selection[table]
  table:
    Table: ref_1
  predicates:
    IsNull[array(boolean)]
      filter = Column[array(null)] 'filter' from table 
        ref_1

col = Column[array(int32)] 'col' from table 
  ref_2 does not fully originate from dependencies of the table expression.
```

I have time to look deeper into this tomorrow. If I'm doing something wrong or if there is a good place to start looking for a fix please let me know!

**Comment by maxmzkr** [comment]
I actually just pulled master again and I'm getting this error now

```
support@docker-host-unknown:~/ibis$ python ibis_fail.py 
SELECT `col`, count(*) OVER () AS `count`
FROM (
  SELECT `col`
  FROM (
    SELECT *
    FROM (
      SELECT `col`, NULL AS `filter`
      FROM t
    ) t2
    WHERE `filter` IS NULL
  ) t1
) t0
Traceback (most recent call last):
  File "ibis_fail.py", line 16, in <module>
    t[t.columns]
  File "/home/support/ibis/ibis/expr/types.py", line 607, in __getitem__
    return self.projection(what)
  File "/home/support/ibis/ibis/expr/api.py", line 2058, in projection
    op = projector.get_result()
  File "/home/support/ibis/ibis/expr/analysis.py", line 685, in get_result
    fused_op = self._check_fusion(roots[0])
  File "/home/support/ibis/ibis/expr/analysis.py", line 725, in _check_fusion
    elif validator.validate(lifted_val):
  File "/home/support/ibis/ibis/expr/analysis.py", line 764, in validate
    if self._among_roots(op.table.op()):
  File "/home/support/ibis/ibis/expr/analysis.py", line 777, in _among_roots
    return self.roots_shared(node) > 0
  File "/home/support/ibis/ibis/expr/analysis.py", line 782, in roots_shared
    if root.is_ancestor(node):
  File "/home/support/ibis/ibis/expr/operations.py", line 1741, in is_ancestor
    table = table.op().table
AttributeError: 'UnboundTable' object has no attribute 'table'
```

**Comment by cpcloud** [comment]
I will try to take a look tonight. Shouldn't be too hard to track down.

**Comment by cpcloud** [comment]
@maxmzkr Did this ever work for you in the past? A regression will be easier to debug.

**Comment by maxmzkr** [comment]
I haven't tried it in any older versions

**Comment by cpcloud** [comment]
Cool, thanks.

**Comment by maxmzkr** [comment]
In the case that anyone else runs into this in the mean time, you can do a projection directly with the string values and everything seems to work, so replace the last line with

```
t.projection(t.columns)
```

This seems to be enough to "fix up" the table. After doing the projection, everything works as expected.

**Comment by cpcloud** [comment]
@maxmzkr Very interesting. After I get to the bottom of this we should probably unify the code path here and make these expressions equivalent.
